### ISSUE TITLE
Samsung galaxy s3 mini no looping of gradient transition

### ISSUE THREAD

**Issue by squallsama** [dynamitechetan/Flowing-Gradient#3]
After one transition appear after it it will not happened. 
        FlowingGradientClass grad = new FlowingGradientClass();
        grad.setBackgroundResource(R.drawable.translate)
                .onRelativeLayout((RelativeLayout) findViewById(R.id.musicBg))
                .setTransitionDuration(4000)
                .start();

**Comment by dynamitechetan** [comment]
try to keep the duration same in translate.xml and java ..

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<animation-list xmlns:android="http://schemas.android.com/apk/res/android"  android:id="@+id/selected" android:oneshot="false">
    <!-- The drawables used here can be solid colors, gradients, shapes, images, etc. -->
    <item android:drawable="@drawable/one" android:duration="4000"  />
    <item android:drawable="@drawable/two" android:duration="4000" />
    <item android:drawable="@drawable/three" android:duration="4000" />
    <item android:drawable="@drawable/four" android:duration="4000" />
</animation-list>
```

make it 4000 in xml and in java.
